name: Build CV PDF

on:
  push:
    branches: [ "main" ]
    paths:
      - "README.md"
      - "cv/**"
      - ".github/workflows/build-cv.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install TeXLive (for PDF)
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-extra

      - name: Build PDF from README.md
        run: |
          mkdir -p dist
          pandoc README.md \
            --from=gfm \
            --pdf-engine=xelatex \
            -V geometry:margin=1in \
            -o dist/Girlane_Domingues_CV.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdf
          path: dist/Girlane_Domingues_CV.pdf
